### ISSUE TITLE
Rewrote `&lt;` to `<`, causing a build error

### ISSUE THREAD

**Issue by kategengler** [dyfactor/dyfactor-plugin-disambiguate-locals#3]
I have some code that looks like
`<td>&lt;100 %</td>`

Running `dyfactor run template disambiguate-locals ./app --level modify` rewrote this to `<td><100 %</td>` and caused a build error. Running the plugin then failed with:

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at telemetry.data.forEach (/Users/katie/dev/steadfast/compass/node_modules/dyfactor-plugin-disambiguate-locals/dist/index.js:210:20)
    at Array.forEach (<anonymous>)
    at default_1.modify (/Users/katie/dev/steadfast/compass/node_modules/dyfactor-plugin-disambiguate-locals/dist/index.js:209:24)
    at ModifyModeImpl.modify (/Users/katie/.config/yarn/global/node_modules/dyfactor/dist/commonjs/src/runtime/mode.js:118:21)
    at Runner.<anonymous> (/Users/katie/.config/yarn/global/node_modules/dyfactor/dist/commonjs/src/runtime/runner.js:35:26)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/katie/.config/yarn/global/node_modules/dyfactor/dist/commonjs/src/runtime/runner.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

**Comment by kategengler** [comment]
In another place, passing an option to component like so:
`placeholder='Choose a "creative term here"'` causes a build error as it is rewritten with double quotes in place of the single quotes `"Choose a "creative term here""`

**Comment by krisselden** [comment]
This PR fixes the glimmer printer https://github.com/glimmerjs/glimmer-vm/pull/834

**Comment by kategengler** [comment]
Updating to `@glimmer/syntax` 0.35.7 here, in `ember-template-recast`, and in `dyfactor` fixes the problem with`&lt;`.

The quotation problem in my comment above still happens though, would you prefer I make that another issue?
